version: '3.9'

services:
  web:
    build: .
    volumes:
      - ./:/var/www/html
    ports:
      - "8086:80"
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: sistema_db
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: sistema
      MYSQL_USER: cristina
      MYSQL_PASSWORD: 12345
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sistema.sql:/docker-entrypoint-initdb.d/sistema.sql

  phpmyadmin:
    image: phpmyadmin:5.2.2
    restart: always
    ports:
      - "8085:80"
    environment:
      PMA_HOST: db
      PMA_USER: cristina
      PMA_PASSWORD: 12345
    depends_on:
      - db

volumes:
  db_data:
